use_frameworks!

target 'Fixer_Example' do
  pod 'Fixer', :path => '../'
  pod 'MBProgressHUD'

  target 'Fixer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.9.0'
  end
end
